name: Generate and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'scripts/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # --- 1. Checkout repository ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 2. Set up Node.js for OpenAPI generation ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node deps
        run: npm ci

      # --- 3. Generate openapi.yaml ---
      - name: Generate OpenAPI schema
        run: npm run openapi:generate

      # Verify that the file was created
      - name: Verify OpenAPI file exists
        run: test -f dist/docs/openapi.yaml

      - name: Copy OpenAPI file to docs
        run: cp dist/docs/openapi.yaml docs/content/openapi.yaml

      # --- 4. Set up Python and MkDocs ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs and plugins
        working-directory: docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- 5. Build MkDocs site ---
      - name: Build MkDocs site
        working-directory: docs
        run: mkdocs build --clean
    
        
      - name: Copy demo page
        run: cp demo/index.html dist/site/demo.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist/site
  
  deploy:
    needs: build-docs
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4